import { Inter } from "next/font/google";
import "./globals.css";
import pageLayout from "./page.module.css";
import Header from "@/components/global/navbar/Header";
import LeftLayout from "@/components/global/layouts/LeftLayout";


const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "GhettoMusic",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={pageLayout.appLayout}>
           <LeftLayout />
          <div className={pageLayout.rightLayout}>
          <Header />
            <div className={pageLayout.centerRihtLayout}>
            <main>
              <div className={pageLayout.pagecontainer}>
              {children}
              </div>
            </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
